#some built in functions(also called predefined function)
x=[10, 20, 30, 40, 50, 60, 70]
print(x)
print(len(x))
x.append(60)
print(x)
x.insert(2,80)
print(x)
y=['abc', 'def', 'xyz', 30]
print(y)
x.extend(y)
print(x)
print(x.index('abc'))
x.remove(30)
print(x)
x.pop()
print(x)
x.pop(3)
print(x)